studyurl/app/urls.py
from django.urls import path, re_path
from app.views import index, list, article

from .url_pattern_str import ThreeDigitConverter
from django.urls import register_converter

register_converter(ThreeDigitConverter, 'threeint')

urlpatterns = [
    path("indexs/", index, name='index666'), # 善用name參數，未來改url不會在html又改
    path('list/', list, name='list'),
    path('article/<int:id>/', article, name='article'),          # 只匹配數字 
    # # path('article/<str:id>/', article, name='article'),       # 匹配中文 英文 空格 符號
    path('article/<slug:id>/', article, name='article'),         # 匹配數字 字母
    # # path('article/<path:id>/', article, name='article'),        # 匹配中文 英文  空格 符號 數字 /
    # re_path('article/([5-9]{4})/$', article, name='article'),    #正則表達django1
    # re_path('article/(?P<id>[2-5]{2})/$', article, name='article'),
    path('article/<threeint:id>/', article, name='article'),          # 只匹配數字 

]

studyurl/studyurl/urls.py
from django.contrib import admin
from django.urls import path, include
from vueapp import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('appa/', include(('app.urls', 'app'), namespace='appa666')), # 複雜方式，加上namespace，防止二級name重名
    # path('appa/', include('app.urls')), #簡易方式，不能防止name重名
    path('',views.vueindex)
]

studyurl/app/models.py
from django.db import models

# Create your models here.

studyurl/vueapp/models.py
from django.db import models

# Create your models here.

studyurl/app/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.
def index(request):
    return HttpResponse('index page!')

def list(request):
    return render(request, 'list.html')

def article(request, id):
    types = type(id)
    print('值: {},類型 : {}'.format(id, types))
    return render(request, 'app/article.html', {'id': id})

studyurl/vueapp/views.py
from django.shortcuts import render

# Create your views here.
def vueindex(request):
    return render(request, 'index.html')

studyurl/app/templates/app/article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>article</title>
</head>
<body>
    Article: <br>
    值: {{id}}
</body>
</html>

studyurl/app/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>list</title>
</head>
<body>
    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Necessitatibus ab fugit delectus rerum repudiandae voluptatibus earum magni modi dignissimos. Iure ad id excepturi repellendus accusamus recusandae dolorum impedit vitae enim!
    <hr>
    <a href="'/index/">a</a><br>
    <a href="/app/index/">b</a><br>
    <hr>
    <a href="{% url 'appa666:index666' %}">c</a><br>   {% comment %} 'appa666:index666' 避免不同app取的name一樣{% endcomment %}
    <a href="{% url 'appa666:index666' %}">d</a><br>
</body>
</html>

studyurl/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>vue</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
</head>
<body>
    <h1>vue</h1>

    <script src="/static/bootstrap.bundle.min.js"></script>
    <script src="/static/popper.min.js"></script>
    <script src="/static/bootstrap.min.js"></script>
    <script src="/static/vue.global.js"></script>
</body>
</html>